# Configuration for cargo-deny
# See: https://embarkstudios.github.io/cargo-deny/

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# A list of advisory IDs to ignore.
ignore = []

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "0BSD",
    "Zlib",
    "MPL-2.0",
    "AGPL-3.0-only",
]
# The confidence threshold for detecting a license from license text.
confidence-threshold = 0.8

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "allow"
# The graph highlighting used when creating dotgraphs for crates
# with multiple versions
highlight = "all"
# List of crates that are allowed
allow = [
    #"crate_name@version",
]
# List of crates to deny
deny = [
    # Deny old, vulnerable, or problematic crates
    #{ name = "openssl", version = "<0.10" },
]
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
    #"crate_name@version",
]
# Similarly named crates that are not the same
skip-tree = [
    #"crate_name@version",
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is not
# in the allow list is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"
# List of URLs for allowed crate registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of URLs for allowed Git repositories
allow-git = []
